version: "3.8"
services:
  server:
    build:
      context: ./server
    volumes:
      - ./server:/server:delegated
    ports:
      - 5000:5000
    tty: true
    working_dir: /server
    # command: FLASK_APP=app.py flask run -h 0.0.0.0
  front:
    build:
      context: ./front
    volumes:
      - ./front:/front:delegated
    ports:
      - 8000:8000
    tty: true
    working_dir: /front
