version: "3.8"
services:
  server:
    build: .
    volumes:
      - ./:/server:delegated
    ports:
      - 5000:5000
    tty: true
    working_dir: /server
    # command: FLASK_APP=app.py flask run -h 0.0.0.0
